server:
#  servlet:
#    context-path: /learn
  port: 8080

spring:
  application:
    name: learn-test

  profiles:
    active: dev

# mybatis-plus
#mybatis-plus:
#  type-aliases-package: com.example.demo.business.entity
#  mapper-locations: classpath:mappers/*.xml
#  check-config-location: true
mybatis:
  type-aliases-package: com.example.demo.business.entity
  mapperLocations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true