server:
#  servlet:
#    context-path: /learn
  port: 8080

spring:
  application:
    name: learn-test

  profiles:
    active: dev

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 100
        max-wait: -1ms
        max-idle: 100
        min-idle: 0

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456

# actuator 暴露监控访问接口，默认是/health和/info
management:
  endpoints:
    web:
      exposure:
        include: '*'
# actuator 描述信息
info:
  blog-url: http://127.0.0.1
  outhor: LiuLukuan
  version: @project.version@

